### PR TITLE
Bug fixes and new notification to show who played a video.

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by juliocoliveira** [comment]
There is no errors errors relating to IsValid since is global function.
Thanks but is really useless commit, But what counts is the intention.

**Comment by thegrb93** [comment]
playx:IsValid() will error if playx is nil which does happen. If you won't fix the errors then this repository is useless.

**Comment by juliocoliveira** [comment]
I fix the errors that are reported.
As i said i never got that error.

**Comment by juliocoliveira** [comment]
I'm sorry man, I was arrogant saying that your Pull/Commit was useless, But was true i never got an error report about that, And i didn't played Garry's Mod so i never stopped to test the latest Garry's Mod updates.

Just 12 days ago i got the error report: https://github.com/ZionDevelopers/playx/issues/76

I posted your updates and gave credit to you: https://github.com/ZionDevelopers/playx/commit/bc9fd2cf6fe318063f4292091cfd3d9d9a077458

**Pull request closed without merging**
