### PR TITLE
changed the navigators home url to the PlayX's one and not youtube

### PR DESCRIPTION
**Pull request by TR094**

### CODE REVIEW

**Comment by TR094** [comment]
im gonna try to work on the navigator now

**Comment by juliocoliveira** [comment]
you are resubmitting the same code from previous pull request.

**Comment by juliocoliveira** [comment]
Also please don't submit pull requests of one line, Code lots of improvements, changes and etc, then submit, I'll not push one line only.

**Comment by TR094** [comment]
alrighty then

**Pull request closed without merging**
